# Generated by Django 3.2.1 on 2021-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210512_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(default=100),
        ),
    ]
