# Generated by Django 3.2.2 on 2021-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_room_available_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='upload/room'),
            preserve_default=False,
        ),
    ]
